// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package db

import (
	"template/internal/service/config"
)

// Injectors from wire.go:

func InitDep() *service {
	dbMap := config.ProvideDbMap()
	service2 := &service{
		DbMap: dbMap,
	}
	return service2
}
