// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package httpEngine

import (
	"template/internal/service/config"
)

// Injectors from wire.go:

func InitDep() *service {
	http := config.ProvideHttp()
	service2 := &service{
		Http: http,
	}
	return service2
}
